import type { Metadata } from "next";
import { StrictMode } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Commander",
  description: "Generated by Oleksandr Ananiev for Qream design agency",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StrictMode>{children}</StrictMode>
      </body>
    </html>
  );
}
